DELETE from MPA;
DELETE from GENRES;
DELETE from FILMS;
DELETE from FILMGENRES;
DELETE from USERS;
DELETE from FILM_DIRECTORS;
DELETE from FEED;
DELETE from FRIENDS;
DELETE from LIKES;
DELETE from REVIEWS;



insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (1, 'Комедия');
insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (2, 'Драма');
insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (3, 'Мультфильм');
insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (4, 'Триллер');
insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (5, 'Документальный');
insert into GENRES (GENRE_ID, GENRE_NAME)
VALUES (6, 'Боевик');

INSERT INTO MPA (MPA_ID, MPA_NAME)
VALUES (1, 'G');
INSERT INTO MPA (MPA_ID, MPA_NAME)
VALUES (2, 'PG');
INSERT INTO MPA (MPA_ID, MPA_NAME)
VALUES (3, 'PG-13');
INSERT INTO MPA (MPA_ID, MPA_NAME)
VALUES (4, 'R');
INSERT INTO MPA (MPA_ID, MPA_NAME)
VALUES (5, 'NC-17');

